### ISSUE TITLE
Reconsider adding `netstandard2.0` support for OpenTelemetry.ResourceDetectors.AWS

### ISSUE THREAD

**Issue by prajon84** [open-telemetry/opentelemetry-dotnet-contrib#1621] opened 2024-03-20 18:45 UTC
# Issue with OpenTelemetry.ResourceDetectors.AWS

Trying to add `OpenTelemetry.ResourceDetectors.AWS` but adding to in-house library project which is in `netstandard 2.0`
But, as per [this PR](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1177), this library has been released in .net6.0 which is not usable in our case.

## Additional Context

Can this library be updated to support for both `net6.0,net8.0` and `netstandard2.0` too something with similar as [this](https://github.com/open-telemetry/opentelemetry-dotnet/blob/af57ae87871aac7e201a03255ac8c81e5747bc07/build/Common.props#L24C5-L24C85)

**Comment by prajon84** [comment] 2024-03-20 20:26
@Kielek

**Comment by prajon84** [comment] 2024-04-04 20:36
👋  @Kielek  I want to consume `OpenTelemetry.ResourceDetectors.AWS` in `netstandard` library project.

**Comment by Kielek** [comment] 2024-04-11 10:10
@prajon84, is there any reason why you cannot retarget you application to modern .NET versions? For now, there is no supported .NET version which is not covered by `net6.0` or `net462` target framework.

@srprash, @ppittle FYI

**Comment by prajon84** [comment] 2024-04-11 12:25
> @prajon84, is there any reason why you cannot retarget you application to modern .NET versions? For now, there is no supported .NET version which is not covered by `net6.0` or `net462` target framework.

Because we are consuming it to in-house library which is `netstandard2.0` not to our applications.

**Comment by at-mk** [comment] 2024-07-11 11:42
Hei @Kielek 
Updating to support .net8 runtimes wouldn't be a problem tho?
I found out that aws instrumenting in an dotnet8 application is not working (whereas http instrumenting for exampel works).
When i switched the runtime to dotnet6 for testing it worked.
If it`s more than just updating the target runtimes, i can open a new issues as well...
Thanks

**Comment by Kielek** [comment] 2024-07-11 11:53
@ppittle, @srprash, could you please check previous comment?

**Comment by at-mk** [comment] 2024-07-11 14:18
> @ppittle, @srprash, could you please check previous comment?

I did some more testing and it turned out that it actually works. The problem is that I do the AWS calls in a referenced project. So let`s say ProjectA starts the App and does the tracing with all of its instrumenting, and it calls Project B which for example sends a request to dynamo. In that case it is only registered as a HTTP request, has nothing to do with the dotnet version :)

**Comment by ppittle** [comment] 2024-07-17 21:00
I haven't yet tried re-adding a NET Standard target, is there a technical impediment?  Per https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1177, are the nullability improvements (which are very nice to have!) not work with NET Standard 2?  Or is there an issue with build/deploy scripts?

If there's no technical challenge, I am ok with re-adding the .NET Standard target to support this use-case.

**Comment by Kielek** [comment] 2024-10-25 09:59
Done in #2164. If you need a release, feel free to create request release. Closing.

**Closed by Kielek** 2024-10-25 09:59 UTC
Labels: comp:resources.aws
