### ISSUE TITLE
[Instrumentation.Runtime] .NET 9 updates and future plans

### ISSUE THREAD

**Issue by joegoldman2** [open-telemetry/opentelemetry-dotnet-contrib#2071] opened 2024-09-14 13:28 UTC
With the introduction of built-in runtime metrics in .NET 9 (https://github.com/dotnet/runtime/pull/104680), I wanted to understand the future plans for OpenTelemetry.Instrumentation.Runtime. Specifically:

- Will the package continue to be maintained and supported for .NET version before 9?
- Are there any plans to phase it out for users who are using .NET 9 or newer?

**Comment by Kielek** [comment] 2024-09-17 12:30
@twenzel, @xiang17  FYI

**Comment by Kielek** [comment] 2024-09-17 12:32
I would say, that we should keep this package.

For .NET Framework and .NET8 (I assume that .NET6 will be removed) we should keep current behavior. For .NET9+ we should register `System.Runtime` in meter.

We have similar behavior for AspNetCore already.

**Comment by twenzel** [comment] 2024-09-17 12:42
@Kielek sounds good to me.

**Comment by xiang17** [comment] 2024-09-18 23:59
Agree to keep current behavior for existing use cases.

**Comment by CodeBlanch** [comment] 2024-09-23 23:12
I'm assuming since the issue isn't assigned to anyone that @twenzel @xiang17 neither of you are actively working on this?

I added "help wanted" tag.

For anyone who wants to pick this up, it sounds like we need to...

* Update the code to call `AddMeter("System.Runtime")` when running on .NET 9+. The existing logic should only run when NOT on .NET 9+.

* Update `README` with information [similar to what we have for AspNetCore](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/7a09ef727844dd7968baee5564d2b1f1c30bf507/src/OpenTelemetry.Instrumentation.AspNetCore/README.md?plain=1#L163-L166).

**Comment by manishrw** [comment] 2024-09-28 09:13
@CodeBlanch I can take it up if it's available.

**Comment by Kielek** [comment] 2024-11-19 10:47
@stevejgordon, There is a silence in more than one month. Feel free to take it.

**Closed** 2024-11-22 07:17 UTC
Labels: good first issue, help wanted, comp:instrumentation.runtime
