### ISSUE TITLE
`OpenTelemetry.Instrumentation.Http`: avoid duplicate addition of tags and potential conflicting logic on .NET 9+

### ISSUE THREAD

**Issue by antonfirsov** [open-telemetry/opentelemetry-dotnet-contrib#2156] opened 2024-10-03 18:07 UTC
### Component

OpenTelemetry.Instrumentation.Http

### Is your feature request related to a problem?

.NET 9 emits standard tags natively, see https://github.com/dotnet/runtime/pull/104251

I didn't have a chance to check how would `OpenTelemetry.Instrumentation.Http` behave on .NET 9, but I think it would be important to test it and remove duplicate (and potential conflicting) logic from [HttpHandlerDiagnosticsListener](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerDiagnosticListener.cs) on .NET 9+.

Note that there are no native enrichment and filtering capabilities yet, users would still need to rely on  `OpenTelemetry.Instrumentation.Http` or on workarounds for that.

### What is the expected behavior?

N/A

### Which alternative solutions or features have you considered?

N/A

### Additional context

N/A

**Comment by TimothyMothra** [comment] 2024-10-03 20:52
I'm closing this as a duplicate of https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/2029

**Closed by TimothyMothra** 2024-10-03 20:52 UTC
Labels: enhancement, comp:instrumentation.http
