### ISSUE TITLE
[Exporter.Geneva] Allow to export only stack trace in logs

### ISSUE THREAD

**Issue by prezaei** [open-telemetry/opentelemetry-dotnet-contrib#2421] opened 2024-12-14 01:38 UTC
### Component

OpenTelemetry.Exporter.Geneva

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry.Api                     | 1.10.0   |
| OpenTelemetry                         | 1.10.0   |

### Runtime Version

net9.0

### Description

I am looking at the Geneva Exporter and there seems to be bug:

![image](https://github.com/user-attachments/assets/79b0e214-357d-4198-8905-12c25107441c)

Exception.ToString() is not the stack trace.... it has a ton more than that...
Can we please fix and limit to the stack trace?
 
Please consider using Exception.StackTrace here which is also cheaper to generate.

### Steps to Reproduce

Log and exception and you see it is not the stack trace that gets exported.

### Expected Result

Just the stack trace to be exported for this property.

### Actual Result

Full Exception Message.

**Comment by prezaei** [comment] 2024-12-14 01:39
@utpilla as FYI. The code is here: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blame/1ca05685cbad63d3fa813b9cab49be341048e69e/src/OpenTelemetry.Exporter.Geneva/Internal/Tld/TldLogExporter.cs#L259

**Comment by cijothomas** [comment] 2024-12-14 02:23
This is not a bug, it is intentional to use ToString() here. OTel SDK upstream uses ToString() for representing exceptions, so if use OTLP Exporter, that is what you'd get. 
It is entirely possible for an opt-in feature flag in GenevaExporter to let users control what representation of Exception is preferred.

I don't recall full details, but I don't think StackTraces takes care of inner_exceptions. Also ToString() takes care of avoiding the async state machine stuff to get cleaner representation. But I can totally see some users preferring StackTrace.

**Comment by cijothomas** [comment] 2024-12-14 02:24
> https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blame/1ca05685cbad63d3fa813b9cab49be341048e69e/src/OpenTelemetry.Exporter.Geneva/Internal/Tld/TldLogExporter.cs#L259

The same is the case when Msgpack encoding is used.

**Comment by prezaei** [comment] 2024-12-14 06:47
> > https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blame/1ca05685cbad63d3fa813b9cab49be341048e69e/src/OpenTelemetry.Exporter.Geneva/Internal/Tld/TldLogExporter.cs#L259
> 
> 
> 
> The same is the case when Msgpack encoding is used.

Why do you think this is intentional? This is called Exception Stack and it is the ToString on Exception.

There is a separate property for exception message here. 

IMHO, this should follow the spec and just be the stack trace and not a repeat of the message + stack trace.

**Comment by cijothomas** [comment] 2024-12-14 17:18
> Why do you think this is intentional? This is called Exception Stack and it is the ToString on Exception.

See the previous discussions on this topic in OTel SDK itself: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1569
"StackTrace" name is what confuses many! The spec wording is "**_A stacktrace as a string in the natural representation for the language runtime. The representation is to be determined and documented by each language SIG._**"

OTel .NET SDK has chosen ex.ToString() as the representation in https://github.com/open-telemetry/opentelemetry-dotnet/pull/5143 (To be precise, it was done in 1.0 itself, but this is where it was documented)

> IMHO, this should follow the spec and just be the stack trace and not a repeat of the message + stack trace.

As shared above, this is already following the spec. Totally open to adding an option to let users decide the representation suitable for them. It should be done upstream in OTel SDK rather than GenevaExporter alone, otherwise users using OTLP Exporter will not be able to take advantage of this flexibility.

**Comment by prezaei** [comment] 2024-12-14 17:22
> > Why do you think this is intentional? This is called Exception Stack and it is the ToString on Exception.
> 
> 
> 
> See the previous discussions on this topic in OTel SDK itself: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1569
> 
> "StackTrace" name is what confuses many! The spec wording is "**_A stacktrace as a string in the natural representation for the language runtime. The representation is to be determined and documented by each language SIG._**"
> 
> 
> 
> OTel .NET SDK has chosen ex.ToString() as the representation in https://github.com/open-telemetry/opentelemetry-dotnet/pull/5143 (To be precise, it was done in 1.0 itself, but this is where it was documented)
> 
> 
> 
> > IMHO, this should follow the spec and just be the stack trace and not a repeat of the message + stack trace.
> 
> 
> 
> As shared above, this is already following the spec. Totally open to adding an option to let users decide the representation suitable for them. It should be done upstream in OTel SDK rather than GenevaExporter alone, otherwise users using OTLP Exporter will not be able to take advantage of this flexibility.

Yes, let's please add an option for StackTrace to actually mean stacktrace... and not some other random string that differs from exception to exception. Thanks

**Comment by cijothomas** [comment] 2024-12-15 17:22
@prezaei I and @rajkumar-rangaraj can help with adding an **opt-in** feature to GenevaExporter to use Exception.StackTrace instead of Exception.ToString().

However, be aware that this will just work for GenevaExporter and will be inconsistent with other systems. I am aware of the below three other places that made the decision to use ToString().

1. If one uses OTLP Exporter, it'll use ToString() only and changing this requires upstream change in OTel SDK itself.

2. ToString() for Exception is also baked into .NET Runtime itself for [Traces](https://github.com/dotnet/runtime/issues/53641) . .NET Exposes API to override the tag values with custom implementation, but not exposed via OTel. (users can still do it)
*Note* that this was a conscious choice in .NET Runtime - the original proposal shows `StackTrace`, but the final approved one uses ToString().

3.  Default LoggerProviders like [ConsoleProvider](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Console/src/SimpleConsoleFormatter.cs#L64) from .NET runtime library also uses ToString().
(They don't call it stacktrace anyway, so no confusion like what we have for Otel!)

**Comment by prezaei** [comment] 2024-12-16 04:38
> @prezaei I and @rajkumar-rangaraj can help with adding an **opt-in** feature to GenevaExporter to use Exception.StackTrace instead of Exception.ToString().
> 
> However, be aware that this will just work for GenevaExporter and will be inconsistent with other systems. I am aware of the below three other places that made the decision to use ToString().
> 
> 1. If one uses OTLP Exporter, it'll use ToString() only and changing this requires upstream change in OTel SDK itself.
> 2. ToString() for Exception is also baked into .NET Runtime itself for [Traces](https://github.com/dotnet/runtime/issues/53641) . .NET Exposes API to override the tag values with custom implementation, but not exposed via OTel. (users can still do it)
>    _Note_ that this was a conscious choice in .NET Runtime - the original proposal shows `StackTrace`, but the final approved one uses ToString().
> 3. Default LoggerProviders like [ConsoleProvider](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Console/src/SimpleConsoleFormatter.cs#L64) from .NET runtime library also uses ToString().
>    (They don't call it stacktrace anyway, so no confusion like what we have for Otel!)

Yes please. Let's add the config to the Geneva one please.
As for ToString use in traces, that makes perfect sense as they are not structures or meant to be structured. They are also not called `Stack`

**Comment by cijothomas** [comment] 2024-12-16 06:13
> As for ToString use in traces, that makes perfect sense as they are not structured or meant to be structured.

Why? Exception conventions for Logs and Spans (Traces) are defined in the exact same way: https://github.com/open-telemetry/semantic-conventions/tree/main/docs/exceptions
If it makes sense for Traces, then it makes sense for Logs too.

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/2422 - I made a quick PR to add StackTrace support. I'll wait for code owners @CodeBlanch and @rajkumar-rangaraj to review. It does add a new public api, but seems very safe to me to ship it as stable.

**Comment by cijothomas** [comment] 2024-12-18 00:24
@CodeBlanch Could you mark this as non-bug, and feature request?

**Closed** 2024-12-18 18:36 UTC
Labels: enhancement, comp:exporter.geneva
