### ISSUE TITLE
OpenTelemetry.Instrumentation.Http 1.7.0 no longer has peer.service attribute

### ISSUE THREAD

**Issue by JamesNK** [open-telemetry/opentelemetry-dotnet-contrib#1761] opened 2024-02-05 12:48 UTC
# Bug Report

We updated Aspire to use OpenTelemetry.Instrumentation.Http from 1.6.0-beta3 to 1.7.0 and HTTP requests no longer have the `peer.service` attribute.

Aspire UI bases some functionality around `peer.service` and that broken when it's no longer present.

## Symptom

**What is the expected behavior?**

I expected to see a peer.service attribute. A HTTP request is accessing a remote service: https://github.com/open-telemetry/semantic-conventions/blob/482cb01c4598429c65dd0b123b30259f41b360cb/docs/general/attributes.md#general-remote-service-attributes

**What is the actual behavior?**

No peer.service attribute.

## Reproduce

Make a HTTP request with 1.6.0-beta3 and see these attributes:

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/303201/5b9f8029-6067-4170-9740-6a3d81688ab7)

Update to 1.7.0 and see these attributes:

![image](https://github.com/open-telemetry/opentelemetry-dotnet/assets/303201/23b3d031-7b94-4b99-9831-0f1fd2af840f)

Note: no peer.service

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom
  projects, so don't point us to such, please.
* If we can not reproduce the behavior you're reporting.

**Comment by martinjt** [comment] 2024-06-02 16:09
I'm inclined to close this issue as it's not a bug, and it's something that we would implement whenever that attribute is stable in the conventions.

**Closed** 2024-06-03 05:22 UTC
Labels: comp:instrumentation.http
