### ISSUE TITLE
EventNameExportMode.ExportAsPartAName does not work when EventId == 0

### ISSUE THREAD

**Issue by kareemshibli96** [open-telemetry/opentelemetry-dotnet-contrib#1524] opened 2024-01-08 11:58 UTC
# Issue with OpenTelemetry.Exporter.Geneva

List of [all OpenTelemetry NuGet
packages](https://www.nuget.org/profiles/OpenTelemetry) and version that you are
using (e.g. `OpenTelemetry 1.3.2`):

OpenTelemetry.Exporter.Geneva 1.6.0
OpenTelemetry.Api 1.6.0

Runtime version (e.g. `net462`, `net48`, `net6.0`, `net7.0` etc. You can
find this information from the `*.csproj` file):

net8.0

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

**What is the expected behavior?**
Geneva exporter should export EventName for log lines with EventId == 0 when EventNameExportMode == EventNameExportMode.ExportAsPartAName .

What do you expect to see?

**What is the actual behavior?**
Geneva exporter export table name instead of EventName.

## Additional Context

in MsgPackLogExporter.cs
    
       // Part A - core envelope
        var eventId = logRecord.EventId;
        bool hasEventId = eventId != default;

        if (hasEventId && this.m_shouldExportEventName && !string.IsNullOrWhiteSpace(eventId.Name))
        {
            // Export `eventId.Name` as the value for `env_name`
            cursor = AddPartAField(buffer, cursor, Schema.V40.PartA.Name, eventId.Name);
            cntFields += 1;
        }
the != operator for struct EventId only compares the int and ignoring the name property.
the default literal for EventId is EventId with int value equals to zero
thus every log line with EventId equals to 0 will have hasEventId == false.

**Comment by rajkumar-rangaraj** [comment] 2024-01-18 00:36
Implementation's focus on non-zero EventIds is intentional and by design. In line with .NET's logging framework, as detailed in the [EventId documentation](https://learn.microsoft.com/en-in/dotnet/api/microsoft.extensions.logging.eventid?view=dotnet-plat-ext-8.0), the `Id` property is the primary identifier for logging events. We strongly encourage users to utilize non-zero EventIds to distinguish their logging events effectively.
 
The decision to use the integer `Id` as the primary identifier, rather than the string `Name`, is fundamentally driven by performance considerations. This approach significantly enhances the efficiency and performance of the log export process, which is critical in high-throughput scenarios. Our implementation aligns with the .NET framework's philosophy, as evidenced by the [EventId's implementation in .NET runtime](https://github.com/dotnet/runtime/blob/6dab58f0213ec67157bdbd09630957e7cc3b1027/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/EventId.cs#L72-L80), where two events are considered equal if they share the same Id.
 
There are no plans to alter this logic, which is rooted in two key factors: firstly, it is an intentional design choice, and secondly, and perhaps most importantly, it is underpinned by solid performance reasons. Altering this approach for edge cases or providing workarounds would not only deviate from our design principles but also potentially compromise performance for the majority of users who adhere to the recommended practices. Our approach prioritizes performance and aligns with the .NET logging framework's standards.

**Comment by vishweshbankwar** [comment] 2024-01-26 16:12
Closing this - See the details above.

**Closed by vishweshbankwar** 2024-01-26 16:12 UTC
Labels: comp:exporter.geneva
